var rrt6 = new Array ();
rrt6[0] = &quot; mendapat &quot;;
rrt6[1] = &quot; mendapatkan &quot;;
rrt6[2] = &quot; memperoleh &quot;;
rrt6[3] = &quot; dapat &quot;;
rrt6[4] = &quot; diberikan &quot;;
var i = Math.floor(5*Math.random());
var rtt7 = new Array ();
rtt7[0] = &quot; info &quot;;
rtt7[1] = &quot; informasi &quot;;
rtt7[2] = &quot; balasan &quot;;
rtt7[3] = &quot; kabar &quot;;
rtt7[4] = &quot; data &quot;;
var i = Math.floor(5*Math.random());
var rrt8 = new Array ();
rrt8[0] = &quot;Tersedia &quot;;
rrt8[1] = &quot;Siap Jual &quot;;
rrt8[2] = &quot;Menyediakan &quot;;
rrt8[3] = &quot;Siap Menjual &quot;;
rrt8[4] = &quot;Siap suplai &quot;;
var i = Math.floor(5*Math.random());
var rtt9 = new Array ();
rtt9[0] = &quot;untuk Anda &quot;;
rtt9[1] = &quot;ke Customer Anda &quot;;
rtt9[2] = &quot;untuk Pelanggan setia Anda&quot;;
rtt9[3] = &quot;ke pelanggan anda &quot;;
rtt9[4] = &quot; &quot;;
var i = Math.floor(5*Math.random());

var r_t = new Array ();
r_t[0] = &quot;Perkenalkan kami dari &quot;;
r_t[1] = &quot;Selamat datang di &quot;;
r_t[2] = &quot;Halo Sahabat &quot;;
r_t[3] = &quot;Ini Persembahan dari &quot;;
r_t[4] = &quot;Informasi untuk Anda, dari &quot;;
r_t[5] = &quot;Persembahan dari &quot;;
r_t[6] = &quot;Tambahan info bagi Anda, dari &quot;;
var i = Math.floor(7*Math.random())

var rt = new Array ();
rt[0] = &quot;. Kali ini kami bagikan untuk anda, informasi &quot;;
rt[1] = &quot;. Inilah informasi tambahan untuk Anda, &quot;;
rt[2] = &quot;. Kami senang berbagi dengan Anda, kali ini &quot;;
rt[3] = &quot;. Info tambahan &quot;;
rt[4] = &quot;. Dapatkan info penjualan, spesifikasi, dan hal yang lain &quot;;
rt[5] = &quot;. Disini Anda bisa mencari info tambahan lebih lengkap &quot;;
rt[6] = &quot;. Kami senang bisa membagikan info produk, penjualan dan lain-lain &quot;;
var i = Math.floor(7*Math.random())

var rrt = new Array ();
rrt[0] = &quot;admin &quot;;
rrt[1] = &quot;marketing &quot;;
rrt[2] = &quot;petugas &quot;;
rrt[3] = &quot;kontak &quot;;
rrt[4] = &quot;nomor WA &quot;;
var i = Math.floor(5*Math.random())

var rtt = new Array ();
rtt[0] = &quot; artikel &quot;;
rtt[1] = &quot; tulisan &quot;;
rtt[2] = &quot;  post &quot;;
rtt[3] = &quot; postingan &quot;;
rtt[4] = &quot; materi &quot;;
var i = Math.floor(5*Math.random())

var rt1 = new Array ();
rt1[0] = &quot; informasi &quot;;
rt1[1] = &quot; manfaat &quot;;
rt1[2] = &quot;  apa yang anda cari &quot;;
rt1[3] = &quot; info &quot;;
var i = Math.floor(4*Math.random())
var rt2 = new Array ();
rt2[0] = &quot; semoga &quot;;
rt2[1] = &quot; mudah-mudahan &quot;;
rt2[2] = &quot; kami harap &quot;;
rt2[3] = &quot; untuk semaksimal mungkin &quot;;
var i = Math.floor(4*Math.random())
var rt3 = new Array ();
rt3[0] = &quot; mengenai &quot;;
rt3[1] = &quot; tentang &quot;;
rt3[2] = &quot; perihal &quot;;
rt3[3] = &quot; dalam hal &quot;;
var i = Math.floor(4*Math.random())

